# Copyright (c) HashiCorp, Inc.

repos:
  - repo: local
    hooks:
      - id: go-gen
        name: go-gen
        entry: go generate ./...
        language: system
        pass_filenames: false
        types: [ text ]
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.1
    hooks:
      - id: gitleaks
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: validate-toml
      - id: go-mod-tidy
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.12.1
    hooks:
      - id: golangci-lint-config-verify
      - id: golangci-lint

